name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners

jobs:
  windows:
    name: 'Windows (JDK 11)'
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 50
    - name: 'Set up JDK 11'
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: 'Test'
      shell: cmd
      run: |
        ./gradlew --no-parallel --no-daemon build javadoc

  linux-avatica:
    name: 'Linux (JDK 13), Avatica master'
    runs-on: ubuntu-latest
    steps:
    - name: 'Set up JDK 13'
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: 'Install Avatica to Maven Local repository'
      run: |
        git clone --branch master --depth 100 https://github.com/apache/calcite-avatica.git ../calcite-avatica
        cd ../calcite-avatica
        ./gradlew publishToMavenLocal -Pcalcite.avatica.version=1.0.0-dev-master -PskipJavadoc
    - uses: actions/checkout@master
      with:
        fetch-depth: 50
    - name: 'Test'
      run: |
        ./gradlew --no-parallel --no-daemon build javadoc -Pcalcite.avatica.version=1.0.0-dev-master-SNAPSHOT -PenableMavenLocal

  mac:
    name: 'macOS (JDK 13)'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 50
      - name: 'Set up JDK 13'
        uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: 'Test'
        run: |
          ./gradlew --no-parallel --no-daemon build javadoc

